name: About
favicon: null
layout_spectrum: 0.053802239475771785
typography_spectrum: 0.9806930013000965
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.02399735734798014
  lightness: 0.5845488065388054
  saturation: 0.1908315832260996
  rhythmicContrast: 0.1340893297456205
purpose: []
